[package]
name = "rusty_renju_image"
version = "0.9.0"
edition = "2024"

[lib]
name = "rusty_renju_image"
crate-type = ["rlib", "cdylib"]

[dependencies]
rusty_renju = { path = "../rusty_renju" }
tiny-skia = "0.11"
webp = "0.3"
fontdue = "0.9"
