[package]
name = "mintaka_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rusty_renju = { path = "../rusty_renju" }
mintaka = { path = "../mintaka" }

serde = { version = "1.0", features = ["derive"] }

wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
