[package]
name = "mintaka_interface"
version = "0.9.0"
edition = "2024"

[[bin]]
name = "pbrain_mintaka"
path = "src/piskvork.rs"

[[bin]]
name = "mintaka_text_protocol"
path = "src/text_protocol.rs"

[[bin]]
name = "mintaka_selfplay"
path = "src/self_play.rs"

[dependencies]
rusty_renju = { path = "../rusty_renju" }
mintaka = { path = "../mintaka" }
num_cpus = "1.17.0"
clap = { version = "4.5", features = ["derive"] }
