[package]
name = "rusty_renju"
version = "0.9.0"
edition = "2024"

[features]
default = ["strict_renju"]
strict_renju = []

[lib]
name = "rusty_renju"
crate-type = ["rlib", "cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = "0.9"

typeshare = "1.0"

[dev-dependencies]
indoc = "2.0"
