[package]
name = "mintaka"
version = "0.1.0-pre-alpha"
edition = "2024"

[features]
debug-statics = []
neural-eval = []
default = []

[dependencies]
rusty_renju = {path = "../rusty_renju" }
serde = { version = "1.0", features = ["derive"] }
lz4 = "1.28"
core_affinity = "0.8.3"

[dev-dependencies]
indoc = "2.0"
